version: '2'
services:
    sboot-app:
        image: sboot
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://sboot-mysql:3306/sboot?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sboot-mysql:
        extends:
            file: mysql.yml
            service: sboot-mysql
